package Controller;

public enum InputType {
    USER_CREATION, ADMIN_CREATION, USER_LOGIN, ADMIN_LOGIN, LOGOUT,SHOW_MY_RESTAURANTS , CREATE_RESTAURANT,
    CHOSE_MY_RESTAURANT, SHOW_MY_FOODS, CHOSE_MY_FOOD , EDIT_RESTAURANT_TYPE, YES, NO, EDIT_FOOD_NAME,
    EDIT_FOOD_PRICE, ADD_FOOD, DELETE_FOOD, DEACTIVATE_FOOD,ACTIVATE_FOOD,
    END , INVALID_ORDER;
}